language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/advanced && pio run && popd
    - pushd examples/ap && pio run && popd
    - pushd examples/basic && pio run && popd
    - pushd examples/smartconfig && pio run && popd
    - pushd examples/wps && pio run && popd
